
GET http://localhost:999/
Content-Type: application.json

GET http://localhost:999/tasks
Content-Type: application.json


POST http://localhost:999/tasks
Content-Type: application.json
{
    "title": "First title from Yac",
    "date": "2022-11-03",
    "description": "This is a first desc from yac!",
    "priority": "normal",
    "status": "todo"
}